language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t dacalvert/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true dacalvert/docker-react npm run test -- --coverage
    